# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v2

      - name: Ruby - Set up
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run bundler
        run: bundle install
      - name: Run tests
        env:
          GEONAMES_USER: ${{ secrets.GEONAMES_USER }}
          GEONAMES_TOKEN: ${{ secrets.GEONAMES_TOKEN }}
        run: bundle exec rake test
